- name: Understanding the gather facts module
  hosts: web  # Target hosts where it will be executed
  become: yes # Root privilege
  gather_facts: yes

 

  tasks:
    - name: gather facts
      debug:
        var: ansible_facts
    - name: gather ipv4 address
      debug:
        var: ansible_facts.all_ipv4_addresses 
    - name: gather distribution_major_version
      debug:
        var: ansible_facts.distribution_major_version 
    - name: gather ipv6 address
      debug:
        var: ansible_facts.all_ipv6_addresses 
