- name: To install apache using gather facts old(AMI 2) and new ami(ami 2023)
  hosts: web  # Target hosts where it will be executed
  become: yes # Root privilege
  gather_facts: yes

 

  tasks:
        
    - name: Install apache in new machine/AMI2023
      dnf:
        name: httpd
        state: present
      when: ansible_facts.distribution_major_version == "2023"
    - name: Install apache in new machine/AMI2023
      yum:
        name: httpd
        state: present
      when: ansible_facts.distribution_major_version == "2"  
