- name: To install apache using gather facts old(AMI 2) and new ami(ami 2023)
  hosts: web  # Target hosts where it will be executed
  become: yes # Root privilege
  gather_facts: yes

 

  tasks:
        
    - name: Installing package in a loop
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - httpd
        - git
        - docker
