- name: Controlling the Apache 
  hosts: web  # Target hosts where it will be executed
  become: yes # Root privilege 
  
  tasks:
    - name: Install Apache
      dnf:
        name: httpd
        state: present
    - name: Start the apache service
      service:
        name: httpd
        state: started
    - name: Copy the file
      copy:
        src: /home/ec2-user/practice/index.html
        dest: /var/www/html/
